# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 283be4d26e0b8a04ca20ada999e0bd2b4819c089855858eadd22f4c78a06448b7b1abc67e3d81b69af9ae45fc82dc75f868c01d468c14e7b512fb7c95d10d147
  oauth:
    client_id: checkapp/admin/application/7
    client_secret: checkapp/admin/application/7
    app_url: http://users-staging.re2n.com/
    scope: “public accounts”

test:
  secret_key_base: 1f3aa6c4546b2c1968d48fec3f950d4ec0b26117c17205f936230f7dfb59a34d48bf8c9d2481e4e33c87a167e4c3af740713f633f957ccf55f86cbffb9a3ad94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
